language: cpp
sudo: required
dist: trusty

os: linux

env:
  global:
    - DISPLAY=:99

before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt58-trusty
  - sudo apt-get update -qq
  - git clone https://github.com/NixOS/patchelf.git
  - cd patchelf
  - bash ./bootstrap.sh
  - ./configure
  - make -j2
  - sudo make install
  - cd -
  - sudo wget -c "https://github.com/probonopd/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage" -O /usr/local/bin/appimagetool
  - sudo chmod a+x /usr/local/bin/appimagetool
  
install:
  - sudo apt-get -y install qt58base qt58declarative qt58webengine binutils xpra

script:
 - ./tests/tests-ci.sh

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash ./upload.sh ./linuxdeployqt-*.AppImage

after_script:
  - "xpra stop :99"

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/

notifications:
  irc:
    channels:
      - "chat.freenode.net#AppImage"
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: always     # options: [always|never|change] default: always
    template:
      - "%{repository} build %{build_number}: %{result} %{build_url}"
    use_notice: true
    # skip_join: true
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4bf20518805a55998cc2
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: always     # options: [always|never|change] default: always

